# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: stores/
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=1000']
    -   id: check-ast # check whether the files ending in .py parse as valid Python
    -   id: check-merge-conflict
    -   id: detect-private-key
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black
        args: []
        files: .
-   repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    -   id: isort
        args: ["--profile", "black"]
        files: .
-   repo: https://github.com/asottile/pyupgrade  # update python syntax
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
